from SinglyLinkedList import SinglyLinkedList

list = SinglyLinkedList()
# 3 5 1 2 4
list.push_front(1)
list.push_back(2)
list.push_front(3)
list.push_back(4)
list.insert(5, 1)
print(list.value_at(3))
print(list.value_n_from_end(3))
print(list.search(3))
list.reverse()
#list.remove(3)
#print(list.search(3))
#print(list.front())
#print(list.back())
print(list.pop_front())
#print(list.erase(0))
print(list.pop_front())
print(list.pop_back())
#print(list.pop_front())
#print(list.pop_front())
print(len(list))
