from BST import BST

bst = BST()
bst.insert(2)
bst.insert(1)
bst.insert(4)
bst.insert(5)
bst.insert(3)
bst.insert(6)
bst.levelorder()
print(bst.get_height())
bst.erase(1)
bst.erase(2)
print(bst.search(2))
print(bst.erase(4))
print(bst.erase(3))
print(bst.search(4))
print(bst.search(5))
print(bst.search(3))
print(bst.get_height())
